- README.md
- learnings.md
Architecture, user stories, overview, learnings.md
relates to #1
> initial readme outline

- .eslintrc.json
- .travis.yml
- package.json
- src/server.js
- tests/test.js
> Install dependencies and make sure test suite works

- .eslintrc.json
- package.json
we broke eslint, oops, just fixed it by re-adding a dependancy
> Fix eslint

- config.env
- database/db_build.js
- database/db_build.sql
- database/db_connection.js
- package.json
Created the initial databases files (db_build.js, db_build.sql and db_connection.js)
Created tables, inserted two initial entries
relates #10
> Set up databases

- src/handlers/handlers.js
- src/router.js
- src/server.js
- tests/test.js
We wrote the basic Node server. We tried to model it on [Dan's](https://github.com/sofer/sssk/blob/master/router.js) but struggled serving public assets so went back to what we knew.
Relates #11
> Wrote server, router & handlers

- public/index.html
the links to index.js and styles.css were wrong in our index.html (they didn't specifiy the directory they were in) so i've just changed them a wee bit.
relates to #17
> fix asset links

- src/handlers/getData.js
- src/handlers/handlers.js
We havel inked our database to our server so that the database runs on ```npm start``` we have also written the query to or database for getting the object htat we will put in the dom
relates to #10
> Connect db to server

- src/handlers/handlers.js
- tests/src/router.test.js
- tests/test.js
Tried to keep these DRY by creating an object of potential routes to test and looping through them with Object.keys to run the same test for each.
Relates #19
> Test router/handlers

- learnings.md
> Adding learnings from getData to learnings file

- public/index.html
- src/createHtml.js
- src/handlers/getData.js
- src/handlers/handlers.js
We created and implemented the createhtml function, so that now index.html is generated based on the database. 
Used template strings: see (here)[http://wesbos.com/template-strings-html]
relates #24
> Create html function

- public/form.html
- public/index.html
- public/styles.css
- public/thanks.html
- src/handlers/handlePost.js
- src/handlers/handlers.js
- src/router.js
We had to add a handler for the `/form` and `/thanks` routes to ensure they're served properly and can POST to `/submit`.
We also wrote a handler for `/submit` that gets the POST data, parses the URL and turns it into the right formatted object.
Relates #26
> Get POST data from form and turn into useful object

- learnings.md
> adding our crazy huge struggle to the learnings

- package.json
- tests/src/createHtml.test.js
It was in dev-dependencies before
> Move pg to dependencies as Heroku needs it

- public/form.html
- public/index.html
- public/styles.css
- public/thanks.html
> Add links to correct places

- public/form.html
- public/styles.css
Add a media query so the text is not so big on mobile.
Also made the buttons more contrasty to pass accessibility tests.
#37
> Fix overflowing text on mobile

- .gitignore
> add config to gitignore. oops

- tests/src/router.test.js
we had a test that tested the post router, but this was actually posting this to the database. Ideally, we would fix this, but time constraints mean that I'm just going to remove this test for the time being, which will take our coverage down.
Relates #48.
> Removed the post router test.

- public/form.html
- public/index.html
- public/thanks.html
We were using `div`s where we should have been using `header` and `nav`.
Relates #45
> Use semantic HTML5 tags for the header section

- README.md
Added installation instructions to the Readme
relates #1 and relates #39
> update Readme with installation instructions

- config.env
> removing config.env

- src/handlers/getData.js
- src/postData.js
If nothnig else this has been an exercise in understanding why writing DRY code is important, therre's a lot of repetition and a lot of room for human errror, and there is a lot of human error. tjere have been lots of problems witj nested if statements, closing of functions, it's essentially been fixed by dilligently console logging and using trial and error to get it to work.
relates to #50
> Fix postData.js
